//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditAutomation.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuditReportDBEntities : DbContext
    {
        public AuditReportDBEntities()
            : base("name=AuditReportDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<AuditCriteria> AuditCriterias { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Datum> Data { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
    }
}
